In [10]:
import numpy as np

A = np.array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]])

A2 = np.linalg.matrix_power(A, 2)

print(A2)

[[3 1 1 2 1 1 0 1 1 0]
 [1 4 0 1 0 2 0 1 2 1]
 [1 0 1 1 1 0 0 0 0 0]
 [2 1 1 5 2 1 0 0 0 1]
 [1 0 1 2 3 0 1 0 1 1]
 [1 2 0 1 0 2 0 1 1 0]
 [0 0 0 0 1 0 1 0 1 0]
 [1 1 0 0 0 1 0 1 1 0]
 [1 2 0 0 1 1 1 1 3 1]
 [0 1 0 1 1 0 0 0 1 3]]


In [25]:
import numpy as np

m = np.zeros((100, 100))

with open("C:\\Users\\rohankant.tatelu\\OneDrive\\dev\\stats-modeling-and-computation\\module-3\\release_directed_graph.txt") as f:
    lines = f.readlines()
    for line in lines:
        m[int(line.split()[0]) - 1][int(line.split()[1]) - 1] += 1
        
edges = np.sum(m)    
print(edges)

trace = np.trace(m)
print(trace)


1030.0
8.0


In [12]:
import numpy as np

A = np.array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]])

m = np.sum(A) / 2
Mod = 0
degree = np.zeros(len(A))
colsum = A.sum(axis=0)/2
rowsum = A.sum(axis=1)/2
degree = colsum + rowsum
type1 = np.array([0,2,4,6,8])
type2 = np.array([1,3,5,7,9])
print(degree)
delta = np.zeros(A.shape)

for i, row in enumerate(A):
    for j, edge in enumerate(row):
        if i in type1 and j in type1 or i in type2 and j in type2:
            delta[i,j] = 1
        Mod += (edge - degree[i] * degree[j] / (2*m)) * delta[i,j]
        
print(Mod/(2*m))

[3. 4. 1. 5. 3. 2. 1. 1. 3. 3.]
-0.2041420118343195


In [14]:
import networkx as nx

A = nx.DiGraph(np.array([[1,0,0,0],
    [1,0,0,0],
    [1,0,0,0],
    [1,0,0,0]]))

C = nx.eigenvector_centrality(A)

print(C)


{0: 0.9999999999986358, 1: 9.536770448968605e-07, 2: 9.536770448968605e-07, 3: 9.536770448968605e-07}


In [15]:
A = nx.DiGraph(np.array([[1,1,1,1],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]]))

C = nx.eigenvector_centrality(A)

print(C)

{0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5}


In [16]:
A = nx.DiGraph(np.array([[1,1,1,1],
    [1,0,0,0],
    [1,0,0,0],
    [1,0,0,0]]))

C = nx.eigenvector_centrality(A)

print(C)

{0: 0.7991714905460788, 1: 0.34704703269074766, 2: 0.34704703269074766, 3: 0.34704703269074766}


In [19]:
A = nx.DiGraph(np.array([[0,1,1,1],
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]]))

C = nx.katz_centrality(A)

print(C)

{0: 0.464739412340173, 1: 0.5112133535741904, 2: 0.5112133535741904, 3: 0.5112133535741904}


In [22]:
A = nx.DiGraph(np.array([[0, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0]]))

K = nx.katz_centrality(A)
P = nx.pagerank(A)

print(P)

{0: 0.34304516922104655, 1: 0.12178517428468952, 2: 0.12178517428468952, 3: 0.12178517428468952, 4: 0.12178517428468952, 5: 0.09978782025635273, 6: 0.07002631338384244}


In [23]:
A = nx.DiGraph(np.array([[0, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0]]))

C = nx.hits(A)

print(C)

({0: 0.2544010361540635, 1: 0.13175928388048824, 2: 0.13175928388048824, 3: 0.13175928388048824, 4: 0.13175928388048824, 5: 0.08680254444349543, 6: 0.13175928388048824}, {0: 0.2544010361540633, 1: 0.13175928388048824, 2: 0.13175928388048824, 3: 0.13175928388048824, 4: 0.13175928388048824, 5: 0.13175928388048824, 6: 0.08680254444349549})


c:\Users\rohankant.tatelu\AppData\Local\Programs\Python\Python310\lib\site-packages\networkx\algorithms\link_analysis\hits_alg.py:78: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  A = nx.adjacency_matrix(G, nodelist=list(G), dtype=float)


In [27]:
A = nx.from_numpy_matrix(np.array([
    [0, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 1, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0]]))

V = nx.linalg.algebraicconnectivity.fiedler_vector(A)

print(V)

[-0.37147145 -0.33561672 -0.234974   -0.33561672  0.01167123  0.25606343
  0.45102474  0.55891949]


<class 'networkx.utils.decorators.argmap'> compilation 25:4: FutureWarning: laplacian_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.


In [2]:
import pandas as pd
import networkx as nx
phases = {}
G = {}
for i in range(1,12): 
  var_name = "phase" + str(i)
  file_name = "https://raw.githubusercontent.com/ragini30/Networks-Homework/main/" + var_name + ".csv"
  phases[i] = pd.read_csv(file_name, index_col = ["players"])
  phases[i].columns = "n" + phases[i].columns
  phases[i].index = phases[i].columns
  phases[i][phases[i] > 0] = 1
  G[i] = nx.from_pandas_adjacency(phases[i])
  G[i].name = var_name
  
print(G[2], G[6], G[10])

Graph named 'phase2' with 24 nodes and 28 edges Graph named 'phase6' with 27 nodes and 47 edges Graph named 'phase10' with 42 nodes and 50 edges


In [5]:
nx.draw(G[2], pos=nx.drawing.nx_agraph.graphviz_layout(G[2]), with_labels=True)  

ImportError: requires pygraphviz http://pygraphviz.github.io/